version: "3"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  web:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - serverName=node-app-1
    volumes:
      - ./src:/usr/src/app/src
      - ./types:/usr/src/app/types
      - ./node_modules:/usr/src/app/node_modules
    ports:
      - "3000:3000"
    command: yarn dev
    depends_on:
      - redis
